export const vediodata = [
  {
    id: 1,
    img: "./courseimg/course.jpg",
    head: "3D Printing",
    v1: "25+",
    v2: "5+",
    v3: "38+",
    c1: "Concepts",
    c2: "Experiments",
    c3: "Quizzes",
    pera: "Use the online image color picker above to select a color and get the HTML Color Code of this pixel. Also you get the HEX color code value, RGB value and HSV value.",
  },
  {
    id: 2,
    img: "./courseimg/course.jpg",
    head: "3D Printing",
    v1: "25+",
    v2: "5+",
    v3: "38+",
    c1: "Concepts",
    c2: "Experiments",
    c3: "Quizzes",
    pera: "Use the online image color picker above to select a color and get the HTML Color Code of this pixel. Also you get the HEX color code value, RGB value and HSV value.",
  },
  {
    id: 3,
    img: "./courseimg/course.jpg",
    head: "3D Printing",
    v1: "25+",
    v2: "5+",
    v3: "38+",
    c1: "Concepts",
    c2: "Experiments",
    c3: "Quizzes",
    pera: "Use the online image color picker above to select a color and get the HTML Color Code of this pixel. Also you get the HEX color code value, RGB value and HSV value.",
  },
];