export const coursedata = [
  {
    id: 1,
    img: "./courseimg/course.jpg",
    imgpro: "./courseimg/course.jpg",
    head: "3D Printing",
    v1: "25+",
    v2: "5+",
    v3: "38+",
    c1: "Concepts",
    c2: "Experiments",
    c3: "Quizzes",
    price: 100,
    toolname: "Glider Junior",
    productContent:
      "Let your child learn as they play. We teach your kids to practically learn aerodynamics by making and flying their own plane with just a pape aerodynamics by making and flying their own plane with just a paper",
    pera: "Use the online image color picker above to select a color and get the HTML Color Code of this pixel. Also you get the HEX color code value, RGB value and HSV value.",
    duration: "6 Weeks",
    Agegroup: "12-25",
    language: "Tamil and English",
    Level: "Advance",
  },
  {
    id: 2,
    img: "./courseimg/course2.jpg",
    head: "DIY Science-Senior",
    v1: "25+",
    v2: "5+",
    v3: "38+",
    c1: "Concepts",
    c2: "Experiments",
    c3: "Quizzes",
    price: 200,
    productContent:
      "Let your child learn as they play. We teach your kids to practically learn aerodynamics by making and flying their own plane with just a pape aerodynamics by making and flying their own plane with just a paper",
    pera: "Use the online image color picker above to select a color and get the HTML Color Code of this pixel. Also you get the HEX color code value, RGB value and HSV value.",
    duration: "3 Weeks",
    Agegroup: "14-30",
    language: "Tamil",
    Level: "Basics",
  },
  {
    id: 3,
    img: "./courseimg/course3.jpg",
    head: "Glider Junior",
    v1: "25+",
    v2: "5+",
    v3: "38+",
    c1: "Concepts",
    c2: "Experiments",
    c3: "Quizzes",
    price: 300,
    productContent:
      "Let your child learn as they play. We teach your kids to practically learn aerodynamics by making and flying their own plane with just a pape aerodynamics by making and flying their own plane with just a paper",
    pera: "Use the online image color picker above to select a color and get the HTML Color Code of this pixel. Also you get the HEX color code value, RGB value and HSV value.",
    duration: "5 Weeks",
    Agegroup: "12-25",
    language: "English",
    Level: "Medium",
  },
  {
    id: 4,
    img: "./courseimg/course4.jpg",
    head: "App Develop",
    v1: "25+",
    v2: "5+",
    v3: "38+",
    c1: "Concepts",
    c2: "Experiments",
    c3: "Quizzes",
    price: 400,

    pera: "Use the online image color picker above to select a color and get the HTML Color Code of this pixel. Also you get the HEX color code value, RGB value and HSV value.",

    productContent:
      "Let your child learn as they play. We teach your kids to practically learn aerodynamics by making and flying their own plane with just a pape aerodynamics by making and flying their own plane with just a paper",
    duration: "4 Weeks",
    Agegroup: "20-25",
    language: "Tamil & English",
    Level: "Medium",
  },
  {
    id: 5,
    img: "./courseimg/course5.jpg",
    head: "Scratch Junior",
    v1: "25+",
    v2: "5+",
    v3: "38+",
    c1: "Concepts",
    c2: "Experiments",
    c3: "Quizzes",
    price: 500,
    productContent:
      "Let your child learn as they play. We teach your kids to practically learn aerodynamics by making and flying their own plane with just a pape aerodynamics by making and flying their own plane with just a paper",
    pera: "Use the online image color picker above to select a color and get the HTML Color Code of this pixel. Also you get the HEX color code value, RGB value and HSV value.",
    duration: "2 Weeks",
    Agegroup: "12-28",
    language: "English",
    Level: "Advance",
  },
];
